### ISSUE TITLE
Not connected / Network status offline

### ISSUE THREAD

**Issue by FSOL06** [3untz/electron-novo#1]
I can't connect to the network. Don't know why. Any node.

![image](https://user-images.githubusercontent.com/97795464/194312334-39564626-1527-492b-bffa-5ea3fa8f9363.png)

![image](https://user-images.githubusercontent.com/97795464/194312427-18991ea7-e8e4-4f25-a9ae-809d936cabfa.png)

Normally I must have 3 transactions : 

![image](https://user-images.githubusercontent.com/97795464/194312721-5a40e9a5-a131-40eb-8449-456bd41ce485.png)

**Comment by 3untz** [comment]
This was a temporary server issue that has since been resolved. Electron Novo will need more servers in the future.
