### ISSUE TITLE
unconfirmed transaction "solved" Novo-cli abandontransaction "your Txid"

### ISSUE THREAD

**Issue by Nox64** [3untz/electron-novo#3]
Is there a way for the transaction to be cancelled?
I made a transaction and chose a very low commission and this brought me to the fact that it is not confirmed, I have been waiting for 2 and a half days.
maybe some way to increase the commission for it to be confirmed?
![image](https://user-images.githubusercontent.com/125110307/218639542-caac65d5-ae18-4d74-b5fa-52efe12738da.png)

**Comment by du10086** [comment]
Is this problem solved? I also want to ask, I have encountered the same problem, it has been 5 days, I still have not confirmed the state, I can’t cancel it.
![novo](https://github.com/3untz/electron-novo/assets/62828181/bd180c76-4777-41dc-b1e0-306c90a2238d)

**Comment by Nox64** [comment]
I had to abort the transaction with the following command. 
Novo-cli abandontransaction "your Txid"

After 24 hours or less, my money returned to my account
